apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: resumora-live
manifests:
  rawYaml:
    - ./deploy/cloud-run-service.yaml
deploy:
  cloudrun:
    projectid: resumora-live
    region: us-central1
