import {
  BriefcaseBusiness,
  CheckCircle2,
  ClipboardPenLine,
  FileText,
  Headphones,
  Languages,
  Mic2,
  PenLine,
  Shield,
} from "lucide-react";
import {
  BASIC_PRICE_USD,
  ELITE_PRICE_USD,
  PRO_PRICE_USD,
} from "./service-quote-pricing";

/** Shared UI strings (EN/FR) for marketing surfaces. */
export const translations = {
  en: {
    navHome: "Home",
    navTrust: "Trust",
    navServices: "Services",
    navPricing: "Pricing",
    navCapabilities: "Capabilities",
    navDelivery: "Delivery",
    navEngagement: "Engagement",
    navTestimonials: "Stories",
    navContact: "Contact",
    navLogin: "Login",
    navRegister: "Register",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    uploadTitle: "Secure intake",
    uploadText:
      "Encrypted upload for a strategist audit—ATS alignment, scanability, and leadership narrative clarity before prescribing your tier.",
    uploadButton: "Upload document",
    uploadSuccess: "Upload completed successfully.",
    uploadError: "Upload failed. Please try again.",
    uploadHint: "Accepted: PDF, DOC, DOCX · Max sensible executive length.",
    servicesTitle: "Curated capabilities",
    servicesSubtitle:
      "Discrete modules you can compose—each anchored to recruiter behaviour and ATS vendors in market.",
    serviceAction: "Continue",
    serviceCategory: "Line of business",
    capabilitiesTitle: "Enterprise capabilities",
    capabilitiesSubtitle: "Institutional-grade modules mapped to hiring committee expectations.",
    servicesPageTitle: "Services & intake",
    servicesPageSubtitle: "Begin with encrypted upload or explore each delivery lane.",
    pricingTitle: "Transparent pricing",
    pricingSubtitle:
      "Increasing depth, revision allocation, and senior oversight—pricing unchanged across regions.",
    popular: "Most selected",
    selectPlan: "Select plan",
    processing: "Processing…",
    deliveryProtocolsTitle: "Delivery protocols",
    deliveryProtocolsSubtitle:
      "Governed milestones from encrypted intake to ATS-safe export—repeatable for audit and scale.",
    engagementTitle: "Live engagement & momentum",
    engagementSubtitle:
      "Authenticated metrics from Neon-backed interactions—no vanity counters. Follow Resumora for release cadence.",
    engagementFollow: "Follow Resumora",
    engagementFollowing: "Following",
    engagementLike: "Like",
    engagementSave: "Save",
    engagementRequest: "Intent signal",
    engagementTrending: "Trending services",
    engagementMostLiked: "Most liked",
    engagementMostSaved: "Most saved",
    engagementMostRequested: "Most requested",
    engagementDisabled: "Engagement requires database connection (Neon).",
    testimonialsTitle: "Client outcomes",
    testimonialsSubtitle:
      "Selected feedback from executives and senior ICs after repositioning engagements.",
    trustTitle: "Operating metrics sponsors expect",
    trustSubtitle:
      "Consistency you can cite in stakeholder updates—delivery cadence, satisfaction, and scale.",
    trustStrip: "Greenhouse · Lever · Workday · ATS-safe PDF/DOC · Global hiring desks · EN/FR delivery",
    footerTagline:
      "Resumora crafts institutional-grade career collateral for leaders who cannot afford generic.",
    footerColProduct: "Product",
    footerColCompany: "Company",
    footerColLegal: "Legal",
    footerAbout: "About",
    footerServices: "Services",
    footerPricing: "Pricing",
    footerUpload: "Upload",
    footerTrust: "Trust metrics",
    footerCapabilities: "Capabilities",
    footerDelivery: "Delivery",
    footerEngagement: "Engagement",
    footerStories: "Stories",
    footerTerms: "Terms",
    footerPrivacy: "Privacy",
    footerSupport: "Support",
    footerContact: "Contact",
    footerCopy: "© 2026 Resumora. All rights reserved.",
    installPwaTitle: "Install Resumora for faster access",
    installPwaInstall: "Install app",
    installPwaDismiss: "Not now",
    navGroupOverview: "Overview",
    navGroupProduct: "Services & delivery",
    navGroupExperience: "Stories & engagement",
    navGroupSupport: "Company & support",
    sidebarNavLabel: "Enterprise navigation",
    footerAboutLuxury:
      "Executive resume studio — ATS-grade dossiers, bilingual EN/FR delivery, concierge cadence.",
    footerColReach: "Contact",
    footerEmail: "support@resumora.net",
    footerLiveChat: "Live chat",
    footerAutomated247: "24/7 automated acknowledgment on intake",
    footerRefund: "Refund policy",
    footerSystemPolicy: "System & platform policy",
    footerSocial: "Social",
    footerSocialPlaceholder: "Configure NEXT_PUBLIC_SOCIAL_* URLs for icons.",
    footerDockSocial: "Official channels",
    footerDockEngage: "Engage",
    footerEngageLike: "Like",
    footerEngageDislike: "Dislike",
    footerEngageShare: "Share",
    footerEngageRegister: "Register",
    footerShareCopied: "Link copied to clipboard.",
    footerShareFail: "Could not share. Copy resumora.net manually.",
    footerEngageBarLead: "Live sentiment · enterprise engagement",
    freeTestMetaTitle: "Free Test",
    freeTestTitle: "Start Free Test",
    freeTestLead:
      "Select your lane, language, and scope—preview-level review only. No payment. Final delivery unlocks on a paid tier.",
    freeTestEmail: "Work email",
    freeTestService: "Service",
    freeTestLang: "Preferred language",
    freeTestPages: "Page scope",
    freeTestNotes: "Goals or role target (optional)",
    freeTestUpload: "Attach résumé/CV (PDF/DOC/DOCX)",
    freeTestOptional: "Optional",
    freeTestSubmit: "Submit Free Test",
    freeTestSuccess: "Received. Our team will respond with preview guidance—final files require a paid plan.",
    freeTestLimit: "One complimentary preview per email.",
    freeTestDisclaimer:
      "Free Test is a sample/preview intake only. It does not trigger Stripe checkout and is not full production delivery.",
    freeTestNeonError: "Server database is offline—try again after Neon is configured.",
    freeTestDuplicate: "This email already used its Free Test.",
    freeTestErrorGeneric: "Something went wrong. Email support@resumora.net if this persists.",
    freeTestStartCta: "Start Free Test",
    contactPageTitle: "Contact",
    contactMetaDescription: "Reach Resumora support — 24/7 coverage and secure chat.",
    contactHours247: "Support hours: 24 hours a day, 7 days a week.",
    contactAutoConfirm:
      "Configure your mail host so every sender to support@resumora.net receives an automated confirmation reply.",
    contactChatCta: "Open secure chat",
    langSwitcherAria: "Site language",
    langEnglish: "English",
    langFrench: "Français",
    minimalHomeAria: "Resumora home",
    backHome: "Back to home",
    returnHome: "Return home",
    navHomeShort: "Home",
    seoSolutionsEyebrow: "SEO · Solutions",
    heroSecureUploadShort: "Secure upload",
    pricingQuestionsTitle: "Questions before checkout?",
    pricingQuestionsSubtitle: "Concierge routing for enterprise lanes.",
    aboutTitle: "About Resumora",
    aboutLead1:
      "Resumora is a premium resume and career brand studio helping professionals secure stronger interviews and compensation outcomes in global markets.",
    aboutLead2:
      "Our delivery team includes senior resume strategists, recruiters, LinkedIn specialists, and interview coaches.",
    loginTitle: "Login",
    loginSubtitle: "Access your Resumora workspace and engagement-aware analytics.",
    loginEmail: "Email",
    loginPassword: "Password",
    loginSubmit: "Continue",
    loginSignedIn: "Signed in successfully.",
    errInvalidCredentials: "Invalid email or password.",
    errLoginGeneric: "Login failed.",
    registerTitle: "Register",
    registerSubtitle: "Create an account to sync likes, saves, and follows across sessions.",
    registerName: "Full name",
    registerSubmit: "Create account",
    registerCreated: "Account created.",
    errEmailInUse: "That email is already registered.",
    errRegisterGeneric: "Registration failed.",
    dashboardTitle: "Engagement analytics",
    dashboardLead:
      "Aggregates feed BossMind event logs when Neon is configured. Signed-in state:",
    dashboardFollowers: "Followers:",
    dashboardProfiles: "Registered profiles:",
    dashboardNeon: "Neon engagement store:",
    dashboardNeonOffline: "offline",
    dashboardNeonOnline: "online",
    dashboardBackEngagement: "Back to engagement",
    dashboardSignOut: "Sign out",
    dashboardAnonymous: "anonymous visitor",
    dashboardSession: "session",
    cancelTitle: "Payment cancelled",
    cancelLead: "No charges were made.",
    cancelBodyPrefix: "You can return to",
    cancelBodySuffix: "and choose another plan.",
    successVerifying: "Verifying payment",
    successWait: "Please wait while we confirm your payment session.",
    successPaymentTitle: "Payment successful",
    successThanks: "Thank you for choosing Resumora.",
    successVerified: "Your payment has been verified successfully.",
    successInvalidTitle: "Invalid session",
    successInvalidLead: "We could not verify this payment session.",
    successErrorTitle: "Verification error",
    successErrorLead: "Something went wrong while verifying your payment.",
    heroSecureUpload: "Secure upload",
    homeEyebrow: "Executive resume studio",
    homeHeadline: "Institutional-grade career collateral for leaders operating under scrutiny.",
    homeLead:
      "ATS-safe dossiers, bilingual EN/FR delivery, and concierge pacing—without diluting your mandate.",
    homeStripTitle: "Book on resumora.net",
    homeStripSubtitle: "Basic · Professional · Elite plans — secure Stripe checkout.",
    homeStripPrimary: "View pricing",
    homeStripSecondary: "Concierge chat",
    pricingOneTimeNote: "one-time",
    chatSendError: "Could not send. Email support@resumora.net directly.",
    ctaPricingUrl: "resumora.net/pricing",
    engagementMetricFollowers: "Followers",
    engagementMetricRegistrations: "Registered clients",
    engagementMetricNeon: "Neon sync",
    engagementNeonLive: "Live",
    engagementAnalyticsLink: "Analytics dashboard",
    engagementEmptySignals: "Awaiting first signals",
    engagementSubscribeShort: "Updates",
    svcQuoteCustomize: "Configure",
    svcQuoteHide: "Close",
    svcQuoteSummary: "Order summary",
    svcQuoteEstimated: "Scope estimate",
    svcQuoteStripeNote:
      "Secured Stripe checkout charges your selected tier rate. Scope details are relayed to your strategist via order metadata.",
    svcQuoteContinue: "Continue to pricing & checkout",
    svcQuoteTier: "Tier",
    svcQuotePages: "Pages",
    svcQuoteResumeType: "Résumé type",
    svcQuoteLanguage: "Language delivery",
    svcQuoteAddons: "Add-ons",
    svcQuoteDelivery: "Delivery",
    svcTierBasic: "Basic",
    svcTierProfessional: "Professional",
    svcTierElite: "Elite",
    svcPages1: "1 page",
    svcPages2: "2 pages",
    svcPages3: "3 pages",
    svcPages4: "4 pages",
    svcResumeChronological: "Chronological",
    svcResumeHybrid: "Hybrid",
    svcResumeExecutive: "Executive condensed",
    svcLangEn: "English only",
    svcLangFr: "French only",
    svcLangBilingual: "EN + FR pair",
    svcAddonLetter: "Strategic letter",
    svcAddonLinkedin: "LinkedIn sprint",
    svcAddonInterview: "Interview pack",
    svcDeliveryStandard: "Standard cadence",
    svcDeliveryExpedited: "Expedited",
    svcDeliveryRush: "Concierge rush",
    svcQuoteLineTierBase: "Plan base",
    svcQuoteLineExtraPages: "Extra pages",
    svcQuoteLineResumeType: "Format preference",
    svcQuoteLineLanguage: "Localisation uplift",
    svcQuoteLineDelivery: "Accelerated delivery",
    svcQuoteAddon_strategicLetter: "Strategic letter",
    svcQuoteAddon_linkedinSprint: "LinkedIn sprint",
    svcQuoteAddon_interviewPack: "Interview rehearsal",
    pricingFromConfigurator: "From your configuration",
    pricingConfiguratorClear: "Clear saved scope",
  },
  fr: {
    navHome: "Accueil",
    navTrust: "Confiance",
    navServices: "Services",
    navPricing: "Tarifs",
    navCapabilities: "Capacités",
    navDelivery: "Livraison",
    navEngagement: "Engagement",
    navTestimonials: "Récits",
    navContact: "Contact",
    navLogin: "Connexion",
    navRegister: "Inscription",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    uploadTitle: "Réception sécurisée",
    uploadText:
      "Téléversement chiffré pour audit stratège—alignement ATS, lisibilité et clarté de narration avant recommandation de palier.",
    uploadButton: "Téléverser le document",
    uploadSuccess: "Téléversement terminé avec succès.",
    uploadError: "Échec du téléversement. Veuillez réessayer.",
    uploadHint: "Formats : PDF, DOC, DOCX · Longueur exécutive raisonnable.",
    servicesTitle: "Capacités structurées",
    servicesSubtitle:
      "Modules distincts à composer—ancrés sur le comportement recruteur et les ATS du marché.",
    serviceAction: "Poursuivre",
    serviceCategory: "Périmètre",
    capabilitiesTitle: "Capacités entreprise",
    capabilitiesSubtitle: "Modules niveau institutionnel alignés sur attentes de comités de recrutement.",
    servicesPageTitle: "Services & réception",
    servicesPageSubtitle: "Commencez par un téléversement sécurisé ou explorez chaque volet.",
    pricingTitle: "Tarification transparente",
    pricingSubtitle:
      "Profondeur, volume de révisions et supervision senior progressifs—prix USD stable quelle que soit la région.",
    popular: "Le plus choisi",
    selectPlan: "Sélectionner le plan",
    processing: "Traitement…",
    deliveryProtocolsTitle: "Protocoles de livraison",
    deliveryProtocolsSubtitle:
      "Jalons gouvernés—de l’intake chiffré à l’export compatible ATS, reproductibles pour audit et montée en charge.",
    engagementTitle: "Engagement en direct",
    engagementSubtitle:
      "Indicateurs issus d’interactions stockées sur Neon—pas de faux compteurs. Suivez Resumora pour la cadence produit.",
    engagementFollow: "Suivre Resumora",
    engagementFollowing: "Abonné",
    engagementLike: "J’aime",
    engagementSave: "Enregistrer",
    engagementRequest: "Signal d’intention",
    engagementTrending: "Services tendance",
    engagementMostLiked: "Plus aimés",
    engagementMostSaved: "Plus sauvegardés",
    engagementMostRequested: "Plus demandés",
    engagementDisabled: "L’engagement nécessite Neon (base de données).",
    testimonialsTitle: "Résultats clients",
    testimonialsSubtitle:
      "Retours d’exécutifs et profils seniors après missions de repositionnement.",
    trustTitle: "Indicateurs attendus en comité",
    trustSubtitle:
      "Des références opérationnelles—cadence, satisfaction et ampleur—pas des tableaux décoratifs.",
    trustStrip:
      "Greenhouse · Lever · Workday · PDF/DOC compatibles ATS · Recrutement global · Livrables EN/FR",
    footerTagline:
      "Resumora produit des dossiers carrière de niveau institutionnel pour les leaders qui refusent le générique.",
    footerColProduct: "Produit",
    footerColCompany: "Entreprise",
    footerColLegal: "Juridique",
    footerAbout: "À propos",
    footerServices: "Services",
    footerPricing: "Tarifs",
    footerUpload: "Téléversement",
    footerTrust: "Indicateurs",
    footerCapabilities: "Capacités",
    footerDelivery: "Livraison",
    footerEngagement: "Engagement",
    footerStories: "Récits",
    footerTerms: "Conditions",
    footerPrivacy: "Confidentialité",
    footerSupport: "Support",
    footerContact: "Contact",
    footerCopy: "© 2026 Resumora. Tous droits réservés.",
    installPwaTitle: "Installer Resumora pour un accès plus rapide",
    installPwaInstall: "Installer",
    installPwaDismiss: "Plus tard",
    navGroupOverview: "Vue d’ensemble",
    navGroupProduct: "Services & livraison",
    navGroupExperience: "Récits & engagement",
    navGroupSupport: "Entreprise & support",
    sidebarNavLabel: "Navigation entreprise",
    footerAboutLuxury:
      "Studio CV direction — dossiers compatibles ATS, livraison EN/FR, cadence concierge.",
    footerColReach: "Contact",
    footerEmail: "support@resumora.net",
    footerLiveChat: "Chat en direct",
    footerAutomated247: "Accusé automatisé 24h/24 à réception",
    footerRefund: "Politique de remboursement",
    footerSystemPolicy: "Politique système & plateforme",
    footerSocial: "Réseaux",
    footerSocialPlaceholder: "Configurez les URLs NEXT_PUBLIC_SOCIAL_* pour les liens.",
    footerDockSocial: "Canaux officiels",
    footerDockEngage: "Engagement",
    footerEngageLike: "J’aime",
    footerEngageDislike: "Pas pour moi",
    footerEngageShare: "Partager",
    footerEngageRegister: "Inscription",
    footerShareCopied: "Lien copié dans le presse-papiers.",
    footerShareFail: "Partage impossible. Copiez resumora.net manuellement.",
    footerEngageBarLead: "Sentiment en direct · engagement entreprise",
    freeTestMetaTitle: "Test gratuit",
    freeTestTitle: "Démarrer un test gratuit",
    freeTestLead:
      "Choisissez votre offre, la langue et le périmètre—aperçu seulement. Aucun paiement. La livraison complète nécessite un palier payant.",
    freeTestEmail: "E-mail professionnel",
    freeTestService: "Service",
    freeTestLang: "Langue préférée",
    freeTestPages: "Pages",
    freeTestNotes: "Objectif ou cible de rôle (facultatif)",
    freeTestUpload: "Joindre CV (PDF/DOC/DOCX)",
    freeTestOptional: "Facultatif",
    freeTestSubmit: "Envoyer le test gratuit",
    freeTestSuccess:
      "Reçu. Notre équipe répondra avec des repères d’aperçu—les livrables finaux passent par un plan payant.",
    freeTestLimit: "Un aperçu gratuit par e-mail.",
    freeTestDisclaimer:
      "Le test gratuit est une demande d’aperçu uniquement. Pas de paiement Stripe et ce n’est pas une livraison complète.",
    freeTestNeonError: "Base de données indisponible—réessayez après configuration Neon.",
    freeTestDuplicate: "Cet e-mail a déjà utilisé son test gratuit.",
    freeTestErrorGeneric: "Une erreur s’est produite. Écrivez à support@resumora.net si cela continue.",
    freeTestStartCta: "Test gratuit",
    contactPageTitle: "Contact",
    contactMetaDescription: "Contact support Resumora — disponibilité 24h/24 et chat sécurisé.",
    contactHours247: "Disponibilité support : 24h/24, 7j/7.",
    contactAutoConfirm:
      "Configurez votre serveur mail pour qu’un accusé automatisé soit envoyé à chaque message vers support@resumora.net.",
    contactChatCta: "Ouvrir le chat sécurisé",
    langSwitcherAria: "Langue du site",
    langEnglish: "English",
    langFrench: "Français",
    minimalHomeAria: "Accueil Resumora",
    backHome: "Retour à l’accueil",
    returnHome: "Retour à l’accueil",
    navHomeShort: "Accueil",
    seoSolutionsEyebrow: "SEO · Solutions",
    heroSecureUploadShort: "Téléversement",
    pricingQuestionsTitle: "Questions avant paiement ?",
    pricingQuestionsSubtitle: "Routage concierge pour voies entreprise.",
    aboutTitle: "À propos de Resumora",
    aboutLead1:
      "Resumora est un studio premium de CV et de marque carrière qui aide les professionnels à obtenir de meilleurs entretiens et des résultats de rémunération sur les marchés mondiaux.",
    aboutLead2:
      "Notre équipe de livraison réunit des stratèges CV seniors, des recruteurs, des spécialistes LinkedIn et des coachs entretien.",
    loginTitle: "Connexion",
    loginSubtitle: "Accédez à votre espace Resumora et aux analyses d’engagement.",
    loginEmail: "E-mail",
    loginPassword: "Mot de passe",
    loginSubmit: "Continuer",
    loginSignedIn: "Connexion réussie.",
    errInvalidCredentials: "E-mail ou mot de passe invalide.",
    errLoginGeneric: "Échec de la connexion.",
    registerTitle: "Inscription",
    registerSubtitle:
      "Créez un compte pour synchroniser vos interactions (j’aime, sauvegardes, suivis) entre sessions.",
    registerName: "Nom complet",
    registerSubmit: "Créer le compte",
    registerCreated: "Compte créé.",
    errEmailInUse: "Cette adresse e-mail est déjà enregistrée.",
    errRegisterGeneric: "Échec de l’inscription.",
    dashboardTitle: "Analytique d’engagement",
    dashboardLead:
      "Les agrégats alimentent les journaux d’événements BossMind lorsque Neon est configuré. État connecté :",
    dashboardFollowers: "Abonnés :",
    dashboardProfiles: "Profils enregistrés :",
    dashboardNeon: "Stockage engagement Neon :",
    dashboardNeonOffline: "hors ligne",
    dashboardNeonOnline: "en ligne",
    dashboardBackEngagement: "Retour à l’engagement",
    dashboardSignOut: "Se déconnecter",
    dashboardAnonymous: "visiteur anonyme",
    dashboardSession: "session",
    cancelTitle: "Paiement annulé",
    cancelLead: "Aucun débit n’a été effectué.",
    cancelBodyPrefix: "Vous pouvez revenir sur",
    cancelBodySuffix: "et choisir un autre plan.",
    successVerifying: "Vérification du paiement",
    successWait: "Veuillez patienter pendant que nous confirmons votre session de paiement.",
    successPaymentTitle: "Paiement réussi",
    successThanks: "Merci d’avoir choisi Resumora.",
    successVerified: "Votre paiement a été vérifié avec succès.",
    successInvalidTitle: "Session invalide",
    successInvalidLead: "Nous n’avons pas pu vérifier cette session de paiement.",
    successErrorTitle: "Erreur de vérification",
    successErrorLead: "Un problème est survenu lors de la vérification du paiement.",
    heroSecureUpload: "Téléversement sécurisé",
    homeEyebrow: "Studio CV direction",
    homeHeadline: "Dossiers carrière de niveau institutionnel pour cadres sous contrainte.",
    homeLead:
      "Livrables compatibles ATS, livraison bilingue EN/FR et cadence concierge—sans diluer votre mandat.",
    homeStripTitle: "Réservez sur resumora.net",
    homeStripSubtitle: "Plans Basic · Professional · Elite — paiement sécurisé Stripe.",
    homeStripPrimary: "Voir les tarifs",
    homeStripSecondary: "Chat concierge",
    pricingOneTimeNote: "paiement unique",
    chatSendError: "Envoi impossible. Écrivez à support@resumora.net.",
    ctaPricingUrl: "resumora.net/pricing",
    engagementMetricFollowers: "Abonnés",
    engagementMetricRegistrations: "Clients inscrits",
    engagementMetricNeon: "Sync Neon",
    engagementNeonLive: "Actif",
    engagementAnalyticsLink: "Tableau analytics",
    engagementEmptySignals: "En attente de signaux",
    engagementSubscribeShort: "Flux",
    svcQuoteCustomize: "Configurer",
    svcQuoteHide: "Fermer",
    svcQuoteSummary: "Récapitulatif",
    svcQuoteEstimated: "Estimation de périmètre",
    svcQuoteStripeNote:
      "Le paiement Stripe sécurisé facture le palier choisi. Le détail du périmètre est transmis au stratège via les métadonnées de commande.",
    svcQuoteContinue: "Poursuivre vers tarifs & paiement",
    svcQuoteTier: "Palier",
    svcQuotePages: "Pages",
    svcQuoteResumeType: "Type de CV",
    svcQuoteLanguage: "Livraison linguistique",
    svcQuoteAddons: "Options",
    svcQuoteDelivery: "Livraison",
    svcTierBasic: "Basic",
    svcTierProfessional: "Professionnel",
    svcTierElite: "Élite",
    svcPages1: "1 page",
    svcPages2: "2 pages",
    svcPages3: "3 pages",
    svcPages4: "4 pages",
    svcResumeChronological: "Chronologique",
    svcResumeHybrid: "Hybride",
    svcResumeExecutive: "Exécutif condensé",
    svcLangEn: "Anglais seul",
    svcLangFr: "Français seul",
    svcLangBilingual: "Paire EN + FR",
    svcAddonLetter: "Lettre stratégique",
    svcAddonLinkedin: "Sprint LinkedIn",
    svcAddonInterview: "Pack entretien",
    svcDeliveryStandard: "Cadence standard",
    svcDeliveryExpedited: "Accéléré",
    svcDeliveryRush: "Rush concierge",
    svcQuoteLineTierBase: "Base du palier",
    svcQuoteLineExtraPages: "Pages supplémentaires",
    svcQuoteLineResumeType: "Préférence de format",
    svcQuoteLineLanguage: "Supplément bilingue",
    svcQuoteLineDelivery: "Livraison accélérée",
    svcQuoteAddon_strategicLetter: "Lettre stratégique",
    svcQuoteAddon_linkedinSprint: "Sprint LinkedIn",
    svcQuoteAddon_interviewPack: "Répétitions entretien",
    pricingFromConfigurator: "Depuis votre configuration",
    pricingConfiguratorClear: "Effacer le périmètre enregistré",
  },
};

export function processSteps(lang) {
  return lang === "en"
    ? [
        {
          title: "Secure upload",
          detail: "Encrypted intake, role classification, and scope lock.",
          step: "01",
          Icon: FileText,
        },
        {
          title: "ATS + human audit",
          detail: "Parser logic crossed with recruiter skim heuristics.",
          step: "02",
          Icon: Shield,
        },
        {
          title: "Executive rewrite",
          detail: "Structure, KPI density, and leadership tone rebuilt.",
          step: "03",
          Icon: ClipboardPenLine,
        },
        {
          title: "Polish & release",
          detail: "ATS-safe layout validation and final artefact handoff.",
          step: "04",
          Icon: CheckCircle2,
        },
      ]
    : [
        {
          title: "Téléversement sécurisé",
          detail: "Réception chiffrée, qualification du poste et périmètre figé.",
          step: "01",
          Icon: FileText,
        },
        {
          title: "Audit ATS + humain",
          detail: "Parseur croisé avec heuristiques de lecture recruteur.",
          step: "02",
          Icon: Shield,
        },
        {
          title: "Réécriture exécutive",
          detail: "Structure, densité KPI et ton de direction reconstruits.",
          step: "03",
          Icon: ClipboardPenLine,
        },
        {
          title: "Finitions & remise",
          detail: "Validation mise en page ATS-safe et livraison finale.",
          step: "04",
          Icon: CheckCircle2,
        },
      ];
}

export function testimonialsList(lang) {
  return lang === "en"
    ? [
        {
          quote:
            "They reframed my mandate without diluting my voice. Quality callbacks inside two weeks.",
          author: "Morgan L.",
          role: "Director of Product, Fintech",
        },
        {
          quote: "Finally, ATS pass-through matched how strong my operating record actually reads.",
          author: "James K.",
          role: "VP Engineering",
        },
        {
          quote: "Bilingual EN/FR packs unlocked Paris and Montréal searches with one coherent narrative.",
          author: "Amélie R.",
          role: "Strategy Lead",
        },
      ]
    : [
        {
          quote:
            "Ils ont recadré mon mandat sans diluer ma voix. Retours qualité en moins de deux semaines.",
          author: "Morgan L.",
          role: "Directrice produit, fintech",
        },
        {
          quote: "Enfin un passage ATS à la hauteur de mon historique opérationnel réel.",
          author: "James K.",
          role: "VP ingénierie",
        },
        {
          quote: "Les livrables bilingues EN/FR ont débloqué Paris et Montréal avec une narration unique.",
          author: "Amélie R.",
          role: "Lead stratégie",
        },
      ];
}

export const SERVICE_LABELS = {
  en: {
    svc_ats: "ATS optimisation",
    svc_letter: "Strategic letter",
    svc_linkedin: "LinkedIn relaunch",
    svc_interview: "Interview prep",
    svc_tls: "Translation / TLS",
    svc_support: "Priority support",
  },
  fr: {
    svc_ats: "Optimisation ATS",
    svc_letter: "Lettre stratégique",
    svc_linkedin: "Relance LinkedIn",
    svc_interview: "Préparation entretien",
    svc_tls: "Traduction / TLS",
    svc_support: "Support prioritaire",
  },
};

export const servicesByLang = {
  en: [
    {
      resourceKey: "svc_ats",
      category: "Resume strategy",
      title: "ATS resume optimisation",
      description:
        "Full-spectrum rewrite with lexical precision, parser-safe layout, and section flow proven across major ATS vendors.",
      ctaHref: "/services#intake",
      ctaLabel: "Upload for review",
      Icon: FileText,
    },
    {
      resourceKey: "svc_letter",
      category: "Application assets",
      title: "Strategic cover letter",
      description:
        "Narratives tied to mandate, culture cues, and quantified proof so submissions feel bespoke at scale.",
      ctaHref: "/services#intake",
      ctaLabel: "Start with intake",
      Icon: PenLine,
    },
    {
      resourceKey: "svc_linkedin",
      category: "Personal brand",
      title: "LinkedIn repositioning",
      description:
        "Authority-forward headline, featured media, and discoverability calibrated to recruiter search norms.",
      ctaHref: "/pricing",
      ctaLabel: "Select tier",
      Icon: BriefcaseBusiness,
    },
    {
      resourceKey: "svc_interview",
      category: "Interview readiness",
      title: "Interview preparation",
      description:
        "Scenario drills and executive presence aligned to your reconstructed dossier—not generic scripts.",
      ctaHref: "/pricing",
      ctaLabel: "Book preparation",
      Icon: Mic2,
    },
    {
      resourceKey: "svc_tls",
      category: "Localisation",
      title: "Translation / TLS",
      description:
        "Native-grade EN/FR pairs with tonal harmonisation across resume, outreach, and follow-up artefacts.",
      ctaHref: "/capabilities",
      ctaLabel: "View capabilities",
      Icon: Languages,
    },
    {
      resourceKey: "svc_support",
      category: "Concierge",
      title: "Priority support",
      description:
        "Concierge pacing, explicit SLAs, and direct escalation whenever velocity is non-negotiable.",
      ctaHref: "/pricing",
      ctaLabel: "Upgrade tier",
      Icon: Headphones,
    },
  ],
  fr: [
    {
      resourceKey: "svc_ats",
      category: "Stratégie CV",
      title: "Optimisation CV ATS",
      description:
        "Réécriture complète, mise en page parseur-safe et enchaînement de sections éprouvé chez les grands ATS.",
      ctaHref: "/services#intake",
      ctaLabel: "Téléverser pour audit",
      Icon: FileText,
    },
    {
      resourceKey: "svc_letter",
      category: "Dossiers candidature",
      title: "Lettre stratégique",
      description:
        "Narratifs reliés au mandat, signaux culture et preuves chiffrées pour un rendu sur-mesure industriel.",
      ctaHref: "/services#intake",
      ctaLabel: "Par l’intake",
      Icon: PenLine,
    },
    {
      resourceKey: "svc_linkedin",
      category: "Marque personnelle",
      title: "Relance LinkedIn",
      description:
        "Titre d’autorité, médias vedettes et découvrabilité calibrées aux usages de recherche recruteur.",
      ctaHref: "/pricing",
      ctaLabel: "Choisir le palier",
      Icon: BriefcaseBusiness,
    },
    {
      resourceKey: "svc_interview",
      category: "Entretien",
      title: "Préparation entretien",
      description:
        "Drills situationnels et présence cadre synchronisés sur votre dossier reconstruit—pas de scripts génériques.",
      ctaHref: "/pricing",
      ctaLabel: "Réserver",
      Icon: Mic2,
    },
    {
      resourceKey: "svc_tls",
      category: "Localisation",
      title: "Traduction / TLS",
      description:
        "Paires EN/FR niveau native avec harmonisation sur tous les artefacts de poursuite.",
      ctaHref: "/capabilities",
      ctaLabel: "Voir les capacités",
      Icon: Languages,
    },
    {
      resourceKey: "svc_support",
      category: "Conciergerie",
      title: "Support prioritaire",
      description:
        "Rythme concierge, SLA explicites et remontée directe lorsque la vitesse est critique.",
      ctaHref: "/pricing",
      ctaLabel: "Monter de palier",
      Icon: Headphones,
    },
  ],
};

export const pricingPlans = [
  {
    id: "basic",
    name: { en: "Basic", fr: "Basic" },
    price: `$${BASIC_PRICE_USD}`,
    env: "NEXT_PUBLIC_STRIPE_PRICE_BASIC",
    featured: false,
    features: {
      en: [
        "Deep ATS remediation pass",
        "Typography + hierarchy upgrade",
        "Industry keyword scaffolding",
        "1 free edit included",
        "One structured revision sprint",
      ],
      fr: [
        "Remédiation ATS approfondie",
        "Hiérarchie typographique premium",
        "Échafaudage mots-clés secteur",
        "1 modification gratuite incluse",
        "Une sprint révision guidée",
      ],
    },
  },
  {
    id: "professional",
    name: { en: "Professional", fr: "Professionnel" },
    price: `$${PRO_PRICE_USD}`,
    env: "NEXT_PUBLIC_STRIPE_PRICE_PRO",
    featured: true,
    features: {
      en: [
        "Everything inside Basic",
        "Full chronological or hybrid rebuild",
        "Role-specific accomplishment mining",
        "2 free edits included",
        "Cover letter authored to spec",
      ],
      fr: [
        "Toutes les garanties Basic",
        "Rebuild chronologique ou hybride",
        "Mining de réalisations cible métier",
        "2 modifications gratuites incluses",
        "Lettre sur-mesure signée strategist",
      ],
    },
  },
  {
    id: "elite",
    name: { en: "Elite", fr: "Élite" },
    price: `$${ELITE_PRICE_USD}`,
    env: "NEXT_PUBLIC_STRIPE_PRICE_ELITE",
    featured: false,
    features: {
      en: [
        "Professional depth + LinkedIn relaunch",
        "Executive storyline workshop",
        "Recorded interview rehearsals",
        "3 free edits included",
        "Dedicated concierge strategist",
      ],
      fr: [
        "Profondeur Professionnel + LinkedIn relancé",
        "Atelier storyline direction",
        "Répétitions entretien enregistrées",
        "3 modifications gratuites incluses",
        "Stratège concierge attitré",
      ],
    },
  },
];

export const performanceStats = {
  en: [
    { value: "98.2%", label: "Client satisfaction", detail: "Measured post-delivery across premium tiers." },
    { value: "4.7×", label: "Interview lift", detail: "Median uplift after completed repositioning." },
    { value: "34h", label: "Median fulfilment", detail: "Operational cadence benchmarked quarterly." },
    { value: "16k+", label: "Professionals served", detail: "From senior IC through EVP mandates." },
  ],
  fr: [
    { value: "98,2 %", label: "Satisfaction client", detail: "Mesurée après livraison sur paliers premium." },
    { value: "4,7×", label: "Lift entretiens", detail: "Hausse médiane après repositionnement mené à terme." },
    { value: "34h", label: "Délai médian", detail: "Cadence opérationnelle revue trimestriellement." },
    { value: "16k+", label: "Profils accompagnés", detail: "Des profils seniors IC aux mandats VP/EVP." },
  ],
};
