#Requires -Version 5.1
<#
.SYNOPSIS
  Pull Hermes secret names from GCP Secret Manager into %LOCALAPPDATA%\hermes\.env
  and write non-secret config.yaml (docker terminal + local API bind).

.DESCRIPTION
  Never prints secret values. Creates the Hermes home directory if missing.
  Windows data dir is %LOCALAPPDATA%\hermes (same shape as Linux ~/.hermes).

.PARAMETER ProjectId
  GCP project (default resumora-live).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\scripts\setup-hermes-local.ps1
#>
[CmdletBinding()]
param(
  [string] $ProjectId = 'resumora-live',
  [string] $HermesHome = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $HermesHome) {
  $HermesHome = Join-Path $env:LOCALAPPDATA 'hermes'
}

New-Item -ItemType Directory -Force -Path $HermesHome | Out-Null

function Get-SecretValue {
  param([string] $SecretId)
  $raw = & gcloud secrets versions access latest --secret=$SecretId --project=$ProjectId 2>$null
  if ($LASTEXITCODE -ne 0 -or -not $raw) { return '' }
  return [string]$raw.Trim()
}

$envPath = Join-Path $HermesHome '.env'
$yamlPath = Join-Path $HermesHome 'config.yaml'

$hermesKey = Get-SecretValue -SecretId 'HERMES_API_KEY'
$serverKey = Get-SecretValue -SecretId 'HERMES_API_SERVER_KEY'
if (-not $serverKey) { $serverKey = Get-SecretValue -SecretId 'API_SERVER_KEY' }

$lines = @(
  '# Generated by scripts/setup-hermes-local.ps1 — do not commit',
  'API_SERVER_ENABLED=true',
  'API_SERVER_HOST=127.0.0.1',
  'API_SERVER_PORT=8642'
)
if ($hermesKey) { $lines += "HERMES_API_KEY=$hermesKey" }
if ($serverKey) { $lines += "API_SERVER_KEY=$serverKey" }

Set-Content -Path $envPath -Value ($lines -join [Environment]::NewLine) -Encoding utf8
try {
  icacls $envPath /inheritance:r /grant:r "${env:USERNAME}:(R,W)" | Out-Null
} catch { }

$yaml = @"
# Non-secret Hermes settings (Windows: %LOCALAPPDATA%\hermes\config.yaml)
terminal:
  backend: docker
gateway:
  api_server:
    enabled: true
    host: 127.0.0.1
    port: 8642
"@
Set-Content -Path $yamlPath -Value $yaml.Trim() -Encoding utf8

Write-Host "Hermes home: $HermesHome"
Write-Host "Wrote config.yaml (no secrets) and .env (key names only in this log)."
if (-not $hermesKey) {
  Write-Host "HERMES_API_KEY secret missing in GCP — add it then re-run this script." -ForegroundColor Yellow
}
if (-not $serverKey) {
  Write-Host "HERMES_API_SERVER_KEY (or API_SERVER_KEY) missing — generate a local bearer and store it in Secret Manager." -ForegroundColor Yellow
}
Write-Host "Next: hermes setup --portal   OR   hermes model"
Write-Host "Then: hermes gateway"
